on:
  push:
    branches: [main, master]

name: "NetLogo Check"
permissions: read-all

jobs:
  run-logolink:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
        version: 'release'
    name: ${{matrix.os}} (${{matrix.version}})
    runs-on: ${{matrix.os}}
    env:
      GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
    permissions:
      contents: write
      pages: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up NetLogo
        uses: danielvartan/logoactions/setup-netlogo@v1
        with:
          version: ${{matrix.version}}
          cache: 'true'

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Install R dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck, any::knitr, any::rmarkdown, local::.
          needs: check

      - name: Install system dependencies
        if: runner.os == 'Linux'
        run: |
          # Install system dependencies

          sudo apt-get update -qq

          sudo apt-get install -y -qq \
            libfontconfig1-dev \
            pandoc
        shell: bash

      - name: Install logolink
        run: |
          # Install logolink

          install.packages("remotes")

          remotes::install_github(
            repo = "danielvartan/logolink",
            auth_token = Sys.getenv("GH_TOKEN")
          )
        shell: Rscript {0}

      - name: Render Quarto
        run: |
          # Render Quarto

          quarto render
        working-directory: './tests/qmd'
